# Generated by Django 6.0.3 on 2026-03-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='graduty_year',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
